### ISSUE TITLE
Add more filters please

### ISSUE THREAD

**Issue by mhendu** [ShanePe/Emby.SmartPlaylist.Plugin#1]
Love this plugin, it makes Emby much more usable. Would be great to have filters for audio language, subtitle language, audio stream codec (e.g., Atmos, DTS-HD, etc.). May be that Emby doesn't capture this but I also have a userrating tag in all my NFO files for my own rating of the content - if Emby stores that I'd love to be able to filter by the movies that I've rated highly.

**Comment by ShanePe** [comment]
Done! In the next release, as for Audio stream codec, I pick up a list from Emby so hope this contains what you're looking for. But I have also added "Stream: Audio Display Title" which is a free text field... Emby normally stores a Display title like "English aac stereo" so you could do a 'containing" filter on that...
