### ISSUE TITLE
Playlists Not Updating

### ISSUE THREAD

**Issue by feerlessleadr** [ShanePe/Emby.SmartPlaylist.Plugin#2]
Hi - running into an issue where my playlists aren't updating after I edit my rules. I have created with the following rule:

`(Series contains Big Bang OR Series contains Abbott Elementary OR Series contains American Auto)`

I then wait a minute for the playlist to populate, and when I navigate to my playlists, I can see all of the episodes for those 3 shows in there. However, when I add 2 new shows to my rules and wait another minute, the playlist doesn't update to include the new series:

`(Series contains Big Bang OR Series contains Abbott Elementary OR Series contains American Auto OR Series contains Better off Ted OR Series contains Brooklyn Nine OR Series contains Community)`

I've run the scheduled update job and I've also restarted the server, but the playlist still shows the same 3 shows. 

If I create a brand new playlist with the new rules, all shows are picked up, but I still have the same issue where if I add any shows to my rules, the changes are not picked up. 

Can you let me know what I'm doing wrong?

EDIT:: If I switch the type from 'Playlist' to 'Collection', then run the sync job, all the shows appear. If I think switch the type back to 'Playlist' from 'Collection', then run the sync job again, all of the shows now appear as they should. So perhaps this is a bug?

**Comment by ShanePe** [comment]
Okay, so I see that you have the mode set to Live. What Live mode does is only look at new items that have changes. So let's say you play one of the newly added episodes you'll see it appear, as Live mode fires whenever there is change to media items it is called often and only on items that have changed. It does not evaluate the entire media library, so the reason you are seeing those is that there has been some kind change to trigger them.

Modes:

Manual: Manually update when clicking the play button only. i.e user controlled.

Live: Only look at new items (and evaluate items already in the list, called often and not performant)

Shuffle: (Daily,  Weekly, Monthly). Clear out the play list and rebuild it based on media library. (Good if you are using limited)

Scheduled: (Daily, Monthly, Weakly). Re-evaluate items already in the playlist, and look at newly added items. 

Hope this helps.
