### ISSUE TITLE
Collections continually edits movie metadata

### ISSUE THREAD

**Issue by nuentes** [ShanePe/Emby.SmartPlaylist.Plugin#3]
I have a simple smart playlist for putting all MCU films into a single collection. It works fine, and I've had it up for months. My only annoyance is that since the Collection/Playlist refreshes daily, it seems that Kodi re-scans these videos daily. So every morning, when I turn my TV on, I see all the MCU films being updated in Kodi. It seems as though the plugin Smart Playlists plugin updates the nfo file for each of the videos daily, regardless of whether it was already in the collection.

Is it possible to only edit a movies metadata on initial add/removal from a collection? I could obviously change the Collection from being live as a workaround, but that obviously means my list won't be current immediately after new films are added.

**Comment by ShanePe** [comment]
I  think this might be a roll on effect from Emby as the smart playlist does not actual update the media items metadata (Other then the playlist.) I stand corrected but what could be happening is that Emby updates the media item to say... "Hey, it's part of this playlist now." and seen and treated like a change.  Live mode is only triggered on metadata changes on items, so not sure why you are seeing changes on the entire playlist. Odd. I think we need to do some further digging here. However, I have made a minor change that might affect this, please let me know on the next release.

**Comment by nuentes** [comment]
Well, collections and playlists work very differently. Playlists are akin to an m3u file, and you can add/remove items on a whim without affecting the movie itself. When a movie is added/removed from a collection, the NFO file for the media itself is updated. Since the NFO is updated, this was triggering Kodi to refresh the movie every single day.

I have no idea why it was happening daily. I believe I had the playlist set to Live, and not Daily. I have turned back on the Smart Playlist that I was using, and will report back.

**Comment by nuentes** [comment]
Could you please re-open this issue, as I don't believe this is resolved.
