### ISSUE TITLE
Not all movies appearing in playlist when multiple versions of media

### ISSUE THREAD

**Issue by nuentes** [ShanePe/Emby.SmartPlaylist.Plugin#4]
I'm honestly not sure if this is an emby issue, or something that can be addressed in this plugin. I have a playlist of all of my 4K movies. It's quite simple:

- Media Type is Movie
- Resolution Width is greater than 2000

When I run the playlist, I get some movies. However, it's not ALL of my 4K media.

![image](https://github.com/ShanePe/Emby.SmartPlaylist.Plugin/assets/13895384/93c64bda-6996-4f6d-bb54-e93888b24820)

For every movie that I have in 4K, I also have a 1080p version

![image](https://github.com/ShanePe/Emby.SmartPlaylist.Plugin/assets/13895384/92d5145f-4794-4420-9c59-6d12898b0ca4)

You can see above that I have Deadpool in 4K (resolution is 3840x2160), however it does not appear in the playlist.

I've pulled a CSV report of my media from Emby before, and seen similarly confusing data for these "Versioned" examples.

**Comment by ShanePe** [comment]
I do a similar thing on my media library, So I can see if there is a better way to identify video streams rather. I have just introduce and audio stream filter, so perhaps I could do one on the video stream. Will let you know. (i.e. "Where video stream contains '4K')

**Comment by ShanePe** [comment]
Okay, so On this, I have added a new Criteria called "Stream: Video Display Title" so you could do a "contains" filter with "4K"

**Comment by nuentes** [comment]
This one appears to still be an issue. It definitely is helping to get a few more of the 4K movies, however it is still not getting Deadpool 1 and 2. I'm sure there are other examples.

![image](https://github.com/ShanePe/Emby.SmartPlaylist.Plugin/assets/13895384/0fec78b0-101c-4fda-bf57-27041db0db37)

![image](https://github.com/ShanePe/Emby.SmartPlaylist.Plugin/assets/13895384/0d146c66-d5ee-4a70-b2ed-dd3838389161)

![image](https://github.com/ShanePe/Emby.SmartPlaylist.Plugin/assets/13895384/008556a2-372c-4b4e-88ff-e1c327d8dcc8)

![image](https://github.com/ShanePe/Emby.SmartPlaylist.Plugin/assets/13895384/e4090883-1549-4574-87be-d09e9c4bea5f)

**Comment by ShanePe** [comment]
Did you have a look through the log to see why it’s not including dead
pool? It might help us try narrow this down.

**Comment by nuentes** [comment]
![image](https://github.com/ShanePe/Emby.SmartPlaylist.Plugin/assets/13895384/f4418048-b07d-4bbf-ad62-a61cbc7122b6)

**Comment by ShanePe** [comment]
This is good, thanks, helps narrow it down. I’ll see what I can find.

**Comment by nuentes** [comment]
Could you please re-open this issue, as I don't believe this is resolved.
