### ISSUE TITLE
Combining 2 Playlists into 1 (honoring Limits)

### ISSUE THREAD

**Issue by nuentes** [ShanePe/Emby.SmartPlaylist.Plugin#5]
I'd like to be able to join 2 playlists into one, and I can't figure out a way to do this. Any ideas? Here is my use case:

I'm trying to perfect my Halloween playlist. I've got a playlist with the majority of what I want working perfectly. It pulls in episodes that include halloween in the title or Overview, as well as many other things. I also have a 2nd playlist of Horror-Comedy TV episodes. When I try to join the rules of the two playlists together into one smart playlist ruleset, I get flooded with WAY too many horror comedy episodes. This is because in my library, I have roughly the same number of horror-comedy episodes as I do Halloween-themed episodes. I want to combine the two playlists in a specific ratio. So I would have 2 helper playlists that feed into a 3rd playlist. The Halloween playlist would be limited to 100, the Horror Comedy playlist limited to 10. They would be joined into a single playlist limited down to 50. In theory, this should leave me with a playlist that is roughly 90% Halloween episodes, and about 10% Horror Comedy.

If it's possible, I'd love to know. Otherwise, I think this might be a feature request. It's a niche request, and I definitely get that.

**Comment by nuentes** [comment]
Also, sorry to create so many issues. You had asked in the emby thread that issues start getting tracked here, so I copy/pasted my unanswered questions.

**Comment by ShanePe** [comment]
Okay, so a possible solution is that there is already functionality (Source Type) to source media items from another playlist and not the main media library. You could use `Source Type: Smart playlist (Execute)` and select Smart Playlist 1 (Which will then execute Smart Playlist 1) and use the result of it for Smart Play List 2. Basically Media Library items -> Smart Playlist 1 -> Smart Playlist 2. Applying rules based  on each. So you could 'chain playlists'. Let me know if that works for you.

**Comment by ShanePe** [comment]
Closing this, let me know if you get it to work.

**Comment by nuentes** [comment]
I am playing around with this, and it doesn't really seem like this is a way to join 2 playlists. This just allows me to further edit an existing playlist. I'll explain again.

- Playlist 1 is all of my Horror Comedies
- Playlist 2 is all of my Halloween movies
- I want to combine the two playlists into Playlist 3. However, I want to limit playlist 1 to 10 items, and limit playlist 2 to 100 items, and then limit Playlist 3 to 50 items, giving me a 1:10 ratio of Playlist 1 to Playlist 2.

**Comment by nuentes** [comment]
Could you please re-open this issue, as I don't believe this is resolved.
