### ISSUE TITLE
Parental rating tag not working

### ISSUE THREAD

**Issue by mhendu** [ShanePe/Emby.SmartPlaylist.Plugin#6]
I use MediaElch to tag all my nfo files, and it places the parental rating inside an mpaa tag, which is I think the preferred tag for Kodi.

So, for example, a tag would look like this:

    <mpaa>PG-13</mpaa>

That does appear to get picked up correctly in Emby as I see the rating next to the movie's runtime.

However, when I try to filter by PG-13 movies using this plugin, the playlist won't save. Can you please check into and advise if I'm doing something incorrectly?

Thanks!

**Comment by ShanePe** [comment]
alrighty, there seems to be a  bit of fuzziness on my end around how Emby manages Parental Ratings... so there is a method to get the parental rating which is what I am using, but on further investigation it seems to be displaying the rating from "Official rating" I have changed the way parental rating now works to rather use official under the hood and it seems to be working as expected. You'll see the parental rating list if now quite large based on your library.
